import type { DemandeClient } from "./types";

// Demandes de démonstration (affichées au premier chargement, avant toute saisie).
export const mockDemandes: DemandeClient[] = [
  {
    id: "dem-1",
    reference: "DC-20260615-001",
    etablissement: "ICP Paris",
    campus: "Campus Bauer",
    ville: "Issy-les-Moulineaux",
    referenceClient: "ICP-2026-06",
    typeEtablissement: "Institut catholique",
    demandeur: { prenom: "Mathilde", nom: "Régnier", fonction: "Pôle Scolarité", email: "scolarite@icp.fr", telephone: "01 44 39 52 00" },
    responsableClient: { prenom: "Hélène", nom: "Duval", fonction: "Responsable des examens", email: "h.duval@icp.fr" },
    demandeurEstResponsable: false,
    responsableSpc: "Jean-Marc Clio",
    emailSpc: "jeanmarcclio@gmail.com",
    lignes: [
      { id: "l1", date: "2026-06-15", creneau: "Matin", salle: "B22", batiment: "B", etudiants: 30, surveillants: 1, pmr: false, tiersTemps: false, debutExamen: "08:30", finExamen: "11:30", debutSurveillance: "08:00", finSurveillance: "12:00" },
      { id: "l2", date: "2026-06-15", creneau: "Matin", salle: "B11", batiment: "B", etudiants: 12, surveillants: 1, pmr: false, tiersTemps: true, debutExamen: "08:30", finExamen: "12:30", debutSurveillance: "08:00", finSurveillance: "13:00", observations: "Tiers-temps — durée majorée 1/3" },
      { id: "l3", date: "2026-06-16", creneau: "Après-midi", salle: "B22", batiment: "B", etudiants: 28, surveillants: 1, pmr: false, tiersTemps: false, debutExamen: "13:30", finExamen: "16:30", debutSurveillance: "13:00", finSurveillance: "17:00" },
    ],
    ttPresence: true,
    ttNombre: 12,
    ttSalles: "B11",
    ttDuree: "Durée majorée 1/3",
    besoinsParticuliers: ["Contrôle d'identité", "Émargement", "Interdiction téléphone"],
    observations: "Session de rattrapages. Prévoir un coordinateur sur site.",
    statut: "À vérifier",
    createdAt: "2026-06-10T09:12:00Z",
    updatedAt: "2026-06-10T09:12:00Z",
    historique: [{ action: "Création demande", date: "2026-06-10T09:12:00Z", detail: "Saisie interne SPC" }],
  },
  {
    id: "dem-2",
    reference: "DC-20260620-001",
    etablissement: "Dauphine PSL",
    ville: "Paris 16e",
    demandeur: { prenom: "Karim", nom: "Haddad", fonction: "Scolarité L3", email: "karim.haddad@dauphine.psl.eu" },
    responsableClient: { prenom: "Karim", nom: "Haddad", fonction: "Scolarité L3", email: "karim.haddad@dauphine.psl.eu" },
    demandeurEstResponsable: true,
    responsableSpc: "Jean-Marc Clio",
    lignes: [
      { id: "l1", date: "2026-06-22", creneau: "Matin", salle: "Amphi A", batiment: "A", etudiants: 180, surveillants: 6, pmr: true, tiersTemps: false, debutExamen: "09:00", finExamen: "12:00", debutSurveillance: "08:30", finSurveillance: "12:30" },
    ],
    pmrPresence: true,
    pmrNombre: 3,
    pmrSalles: "Amphi A",
    statut: "Validée SPC",
    createdAt: "2026-06-14T14:00:00Z",
    updatedAt: "2026-06-16T10:00:00Z",
    historique: [
      { action: "Création demande", date: "2026-06-14T14:00:00Z" },
      { action: "Validation SPC", date: "2026-06-16T10:00:00Z", detail: "Contrôles OK" },
    ],
  },
  {
    id: "dem-3",
    reference: "DC-20260701-001",
    etablissement: "ESSEC",
    ville: "Cergy",
    demandeur: { prenom: "Sophie", nom: "Bernard", fonction: "Admissions", email: "" },
    responsableClient: { prenom: "", nom: "", email: "" },
    responsableSpc: "Jean-Marc Clio",
    lignes: [{ id: "l1", date: "", creneau: "Matin", salle: "", etudiants: 0, surveillants: 0 }],
    statut: "Brouillon",
    createdAt: "2026-07-01T08:30:00Z",
    updatedAt: "2026-07-01T08:30:00Z",
    historique: [{ action: "Création demande", date: "2026-07-01T08:30:00Z" }],
  },
];
